### ISSUE TITLE
Splitter seeking mp2 movie very slow?!

### ISSUE THREAD

**Issue by ujaroe** [Nevcairiel/LAVFilters#101]
Hi,
I'm using the LAV filter splitter (with LAV decoder or Microsoft decoder) for playback of mp2. Unfortunately seeking the file is rather slow, especially seeking forward. It depends on the jump distance - the farther it jumps the longer it takes (up to several seconds). Following seek backwards completes almost immediately.
For me it looks like the splitter tries to read the whole file up to the requested time.
With Windows internal mp2 splitter seeking works okay.
Could you fix this? Or is there some optimization setting?
Thanks!

Edit: FWIW, mediatype of source filters output pin is MEDIATYPE_Stream/MEDIASUBTYPE_MPEG1Video. Usage of LAVsplitter can be prevented when unselecting "raw mpeg" in input formats.
Edit2: Furthermore, sometimes the movie is played such that it looks like it has reduced playback rate: the timecode that's burnt in into the video falls back behind the reported (GetPositions) position.

**Comment by Aleksoid1978** [comment]
Can you upload some file for test.

**Comment by Nevcairiel** [comment]
We would need a video affected by these problems to do anything about this.

**Comment by Nevcairiel** [comment]
I checked the file provided privately, and the key problem is of course that this is raw mpeg video, and not in a container - raw files like this are inherently slow to seek because they don't have any timestamp information, nor do they carry a seeking index, or anything like that.

To offer seeking abilities at all, LAV does in fact read from the front to the start to find the appropriate spot. On my system that barely takes a second or so when seeking right to the end just after opening the file, but if you have even bigger files, this might be more noticeable (or slower file storage)

This file in particular appears to be constant bitrate, so it is theoretically possible to seek simply by translating time into bytes, but this is not something LAV currently implements, since it only works on a very small subset of files (raw constant bitrate), and would require quite some extra assumptions to produce proper timings.

If at all possible I can only recommend to re-mux these streams into containers, even mpegts or mpegps would already help as they carry timestamps and thus allow random access seeking, and anything that can handle a m2v file should also be able to handle a mpg file.

**Comment by ujaroe** [comment]
Okay, thanks for checking! I will see what I can do with remuxing.
Unfortunately, every now and then a customer comes around with some
strangely encoded movie :-(

On some test systems here (old i5 or i7, no SSD) it takes up to 6 or 7
seconds to position short before the end, only the first time though.
Interestingly, the Windows built in Mpeg splitter allows to jump
immediately. Maybe they try to use the CBR info.

How would you like to treat the Github issue?

​

**Comment by filler56789** [comment]
_"Interestingly, the Windows built in Mpeg splitter allows to jump immediately."_

The MPEG splitter from MainConcept (its old versions at least) also can navigate on elementary video streams.

_"Maybe they try to use the CBR info."_

I doubt that, because their trick works with VBR video as well.

As always, Nevcairiel is right, just wrap the elementary streams in a proper container and avoid unnecessary headaches **:-)**

**Comment by ujaroe** [comment]
> The MPEG splitter from MainConcept (its old versions at least) also can navigate on elementary video streams.

Yes - in former times we used the Elecard splitter with good success. But current version is somewhat slow as well and creates artifacts after position changes.

> As always, Nevcairiel is right, just wrap the elementary streams in a proper container and avoid unnecessary headaches :-)

Yes, indeed, this works quite well.

Thanks!
