### ISSUE TITLE
SWF file issue

### ISSUE THREAD

**Issue by gaamaaresosa** [Nevcairiel/LAVFilters#103]
Not all the swf file are opening in Lav Splitter.
Especially swf made from AfterEffects.
I tested Compressed and UnCompressed file too...
Both are like that.
Only few files loading fine.

I have attached the screenshot of grapgedit and a sample swf file too...

NOTE:
I am sorry that I could not upload swf or zip file here.
If you need sample swf files I will upload and send links.

Thanks...
gaamaa

![error](https://cloud.githubusercontent.com/assets/21296884/18036678/53613784-6d8f-11e6-9715-d15a838854ea.jpg)

**Comment by Nevcairiel** [comment]
SWF is a format for interactive animations, not movies. Its not unexpected that most files would not work. Only the most simplistic files which include only video/audio and nothing else would ever work.

For format support, you should test with FFmpeg and then report not-working files to the FFmpeg issue tracker, since LAV just uses the FFmpeg parsing library (libavformat).
