### ISSUE TITLE
RTMP stream playing only 10 seconds.

### ISSUE THREAD

**Issue by gaamaaresosa** [Nevcairiel/LAVFilters#117]
I tried latest LAV version from 0.68 and 0.69
Some RTMP link plays only first 5 seconds.
The same link plays continuously on other players like VLC/VMIX/https://www.hlsplayer.net/rtmp-player
I talked to the video server team. They said some security to play only one viewer at a time in WOWZA.
Except myself (Only one viewer) no one playing.

But LAV Splitter stops after 10 seconds.

Could you pls. fix this ?

gaamaa

**Comment by gaamaaresosa** [comment]
Edit:
I came to know some rtmp stream is from Wowza server and they have configured only one viewer at a time for some security reason.
I think LAV Splitter needs to create a duplicate stream every 5 seconds and kill old stream for some reason.
That is not allowed by this link as it is restricted only one user at a time.
If we do something in LAV then it should work fine.

Now exactly after 5 seconds the stream stops.

gaamaa

**Comment by Nevcairiel** [comment]
RTMP is handled through FFmpeg, you could try if the same problem happens when accessing such a stream through the FFmpeg CLI tool, and if yes, report the issue directly to FFmpeg. I do not directly work on the network protocol parts of FFmpeg, I only use the functionality offered basically out of the box.
