### ISSUE TITLE
Unwanted side effects of the fix for #113

### ISSUE THREAD

**Issue by mkver** [Nevcairiel/LAVFilters#122]
Hello Nevcairiel,

unfortunately your fix for #113 has unwanted side-effects. It can again by reproduced with the [very same file I uploaded last time](https://github.com/Nevcairiel/LAVFilters/files/638545/Skipped.Frames.zip).

| + SimpleBlock (track number 1, 1 frame(s), timecode 0.480s = 00:00:00.480)
|  + Frame with size 45102
| + SimpleBlock (discardable, track number 1, 1 frame(s), timecode 0.380s = 00:00:00.380)
|  + Frame with size 1602
| + SimpleBlock (track number 1, 1 frame(s), timecode 0.400s = 00:00:00.400)
|  + Frame with size 6081
| + SimpleBlock (track number 1, 1 frame(s), timecode 0.420s = 00:00:00.420)
|  + Frame with size 6079
| + SimpleBlock (track number 1, 1 frame(s), timecode 0.440s = 00:00:00.440)
|  + Frame with size 5935
| + SimpleBlock (track number 1, 1 frame(s), timecode 0.460s = 00:00:00.460)
|  + Frame with size 5923
|+ Cluster
| + Cluster timecode: 0.500s
| + SimpleBlock (key, track number 1, 1 frame(s), timecode 0.640s = 00:00:00.640)
|  + Frame with size 48044
| + SimpleBlock (discardable, track number 1, 1 frame(s), timecode 0.560s = 00:00:00.560)
|  + Frame with size 10815
| + SimpleBlock (discardable, track number 1, 1 frame(s), timecode 0.500s = 00:00:00.500)
|  + Frame with size 3662
| + SimpleBlock (track number 1, 1 frame(s), timecode 0.520s = 00:00:00.520)
|  + Frame with size 5051
| + SimpleBlock (track number 1, 1 frame(s), timecode 0.540s = 00:00:00.540)
|  + Frame with size 5048
| + SimpleBlock (track number 1, 1 frame(s), timecode 0.580s = 00:00:00.580)
|  + Frame with size 1981
| + SimpleBlock (track number 1, 1 frame(s), timecode 0.600s = 00:00:00.600)
|  + Frame with size 5238
| + SimpleBlock (track number 1, 1 frame(s), timecode 0.620s = 00:00:00.620)
|  + Frame with size 5238
| + SimpleBlock (track number 1, 1 frame(s), timecode 0.760s = 00:00:00.760)
|  + Frame with size 35275
| + SimpleBlock (discardable, track number 1, 1 frame(s), timecode 0.660s = 00:00:00.660)
|  + Frame with size 988
If I seek to the open GOP-frames (i.e. to the frames with timecodes 0.5s up until 0.62s), the old version of LAV Filters would automatically seek to the keyframe at 0.64; the exception here was Intel QS, which showed a corrupted frame (apparently it started to decode at the keyframe directly preceding (in decoding order) and not at the keyframe preceding it in presentation order). With the current version, both software decoding and DXVA2-decoding result in corrupt output.
I checked the cues and they indeed contain only timecodes of the keyframes and not the cluster timecodes. So if LAV trusted the index (and it should do if it is there and as long as there is no reason to think that this index is damaged/malformed) it should begin decoding the video at the keyframe preceding 0.5s according to PTS -- i.e. at time 0. But it doesn't.
Thanks for investing your valuable time.

Gruß
Andi

**Comment by Nevcairiel** [comment]
Seeking is entirely unaffected by the changes made for #113.

**Comment by mkver** [comment]
It might be that you haven't touched the code for seeking, but nevertheless your change had an impact on it. My guess is that the number of out-of-order frames that LAV guesses used to be reset upon seeking to its low default value and that therefore LAV skipped these open gop-frames and instead showed the next keyframe; but with your changes, it doesn't do that anymore and instead displays these corrupted frames (just like QS always did).

**Comment by Nevcairiel** [comment]
LAV follows the Cue index, but it appears the Cue index is wrong in those files then.

There is a Cue pointing to the start of the second cluster, to 0.640ms, but resuming decoding from that point results in corruption, so its not a clear random access point (ie. not an IDR frame). The definition of "key frame" is a bit muddy with H264, as frames can depend on multiple key frames, so just having one may not guarantee having all of them.

This can be seen by the presentatation order of the timestamps in that cluster. If it would be a clean random access point, then no frames would be in display order before it, but they are.

So for example, seeking to 0.5ms targets the second Cue which points at the second cluster, since the 0.5ms frame is the third frame in that Cluster. It starts at the 0.64ms frame, as its instructed to do.

**Comment by mkver** [comment]
I think you misunderstood me: Resuming decoding from 0.64 on does not result in corruption for the frames that follow the I-frame at 0.64 (actually a recovery point according to the H.264 bitstream) in presentation order (if that's the case, then it wouldn't be legitimately be a keyframe); it just results in corruption for all frames that follow said I-frame in decoding, but not in presentation order, i.e. the frames that are "shared" between the two GOPs. 
My point is that there are cue points for 0.00 and 0.64 (and some later), I want to seek to (say) 0.5 (pts, of course). Then one should seek to the nearest cue point before the position that one wants to seek to (which in this case is 0.00) and start decoding there. If LAV did this, everything would be alright. Instead LAV Filters actually seems to use the cues, seeks to 0.00, parses the file there a bit and sees that the desired frame comes after another I-frame in decoding order, so it just starts at this I-frame. This wouldn't happen if one just trusted the cues.
I do not think that the cues are wrong: They tell you that if you want to seek to a position with a pts>=0.64, you can start decoding at the frame mentioned in this cuepoint. They do not say that everything that follows the frame 0.64 (pts) in decoding order can be safely decoded.

**Comment by Nevcairiel** [comment]
I analyzed this problem further, and while the behavior is not ideal, it is intentional to speed up seeking (and entirely unrelated to the previous fix).

There is a special case in the code where it accepts starting from a future key-frame if said future key-frame is found very close to where the target frame is, in this case the beginning of the cluster. With very long GOPs it could otherwise mean that dozens if not hundreds of frames have to be decoded just to show a very low amount of frames before the new key frame would take over.
