### ISSUE TITLE
Internet access required by installer

### ISSUE THREAD

**Issue by mikescs** [Nevcairiel/LAVFilters#126]
Not so much an 'issue' as a request for info. When running the installer (eg LAVFilters-0.69-Installer.exe) the installer downloads some files from the internet and fails if there's no internet connection. In theatre use the computer used for video playback often doesn't have an internet connection. Is there some way LAVFilters can be installed on a machine that has no internet connection?

**Comment by filler56789** [comment]
Not sure if this will help you, but you can use «UniExtract» for unpacking the installer (.EXE) and then call **regsvr32** to register the **.ax** files manually.
You can download an up-to-date Universal Extractor from:

http://forum.videohelp.com/threads/377808-UniExtract-Universal-Extractor-v-1-6-1?p=2439279

**Comment by blackarcher21** [comment]
Is it because H.264 MVC 3D Decoder checked when install?

**Comment by Nevcairiel** [comment]
If you don't have internet access, just don't enable the MVC 3D component, its the only part that requires internet access. There are no plans to bundle this component directly in the installer, since only a minority of people even need it, and it would almost double the size of the installer itself for everyone.

Otherwise, you can always use the zip bundles which are also being released, they don't have an installer. Don't even need a fancy extraction tool other then something that can unpack plain zip files.

**Comment by mikescs** [comment]
Many thanks - yes, it was the MVC 3D Decoder. I'll look into using the zip bundles.
