### ISSUE TITLE
谁能给我一个完整能编译的包？

### ISSUE THREAD

**Issue by danperor** [Nevcairiel/LAVFilters#130]
经过一天的验证，LAVFilters这个项目就是各种编译不过，却少各种文件，你让去你的2个git链接上下代码，我也下了，放进去还是各种缺少头文件，这个项目是来逗我的吗？
如果有哪位同胞有完整不缺文件能在vs2015下编译通过的可执行包，请发给我，谢谢
87508228@qq.com
另外最好能说明一下你的安装环境，比如除了vs还安装了别的什么组件或者库没有。
既然你说了开源，也放到github上了，就麻烦别设置那么多阻挠，否则我只能理解为只提供编译2进制文件以做一些不可描述的勾当！

**Comment by Neroldy** [comment]
@danperor 你有问题可以好好提问，明明是自己的问题却好像是作者欠了你似的。我使用的是别人编译的LAV，说明其他人也是可以编译通过的。还有请使用英语。
-----------------------------------------------------------------------------------------
Please pay attention to the tone of your question. It's your own problem if you can not compile success, not author's. And I know other guys can compile success because I use his build binary(http://tmod.nmm-hd.org/LAVFilters/).
Finally, in github, use English first.
