### ISSUE TITLE
How to reduce latency for live streaming?

### ISSUE THREAD

**Issue by ShettyRa** [Nevcairiel/LAVFilters#135]
I am performing a live streaming of a video from an IP camera over a web interface.  I am using LAV filter as an encoder on windows and it works fine. 
1. Initially, I had a high latency say about more than 30000ms but I manage to reduce the latency up to 
    600-700ms by changing the camera setup example (fps, bit rate)
2. what I have understood is the lag can be configured by adjusting the buffering size/count to a low value. 
    'I would like to know how can I configure the buffer size of the LAV filter in order to advice low latency as 
    possible'  
   Thank you

**Comment by Nevcairiel** [comment]
LAV isn't really setup for low-latency streaming. In fact, its not really setup for streaming at all, its optimized for file-based playback with faster then realtime data availability. The limited streaming support it has is just there because it basically came for free through the ffmpeg library.

That said, reducing both the network analysis duratioin as well as the queue packet count would possibly help, although I can't say by how much.
