### ISSUE TITLE
Laptop can only use CUVID?

### ISSUE THREAD

**Issue by TheCastleKeeper** [Nevcairiel/LAVFilters#156]
I have an MSI Laptop with an i7, 8 gigs ram, and Nvidia 970M running Windows 10 64bit anniversary home edition.  When I try to use any accelerator mode in LAV video, it uses the IBM video instead of switching to the Nvidia.  In order to get any performance out of LAV, I have to use CUVID; as CUVID taps into the Nvidia card and makes use of it.  I'd like to use d3d11 but it doesn't work.  Just thought I should say something.  I know there are a lot of gaming laptop users out there with duel video boards; ibm for office stuff and nvidia for gaming, etc.  Thanks for all your hard work.

**Comment by Nevcairiel** [comment]
On Optimus Laptops with switchable graphics, its up to the driver to control which GPU gets used. 

Sometimes you can configure it in NVIDIA control panel, sometimes it doesn't let you because NVIDIA thinks forcing the Intel GPU helps to save power (which it does) without giving you an option to override it.

Ultimately, LAV can only use what the drivers make available to it.
