### ISSUE TITLE
Seeking on low quality videos

### ISSUE THREAD

**Issue by Daisenki** [Nevcairiel/LAVFilters#165]
Hi,

madshi meant I should talk with you about that issue, I already made a ticket on his bug tracker about it, but he said it's a decoder problem: http://bugs.madshi.net/view.php?id=508

Could you please look at the data and info?

**Comment by Nevcairiel** [comment]
I can't do anything without a video sample. Note however that mpeg-ts files are not the best format to seek in, and sometimes you just can't do it any better.

**Comment by Daisenki** [comment]
I cut a sample of 10min, the seeking in that sample works without problems, but the complete video not. Why does the seeking work with MPV-Player on the complete video but not with MPC and LAV? 

I upload the complete video (702MB) here, but not sure if you can download it: https://qualy.hdc.bz/ASoS/AKID-041.mp4
If not, I can upload it to rapidgator or shareonline... the video is only a example, I have tons of them with that problem and to say it, it's JAV porn but it's ok, so don't worry. :)

**Comment by Nevcairiel** [comment]
The video has very sparse keyframes (about every 8 to 9 seconds or so), and because of how DirectShow works if you seek right after a keyframe you have to wait until you get the next one, so the clock can "catch up" (ie. the video frame is scheduled to be shown at time X, you have to wait until time X is actually here). Other players that don't use DirectShow may be able to handle this differently by manually adjusting the clock once they find a keyframe, but thats not something DirectShow can do.

Even though your file is named ".mp4", its actually a mpeg-ts file and not mp4, which has no index and as such no good way to find keyframes to seek to, to avoid this problem. More appropriate containers like actual mp4 or mkv don't suffer from this problem, because they have a seeking index.

**Comment by Daisenki** [comment]
Ah ok, so nothing you can do about that. Thanks for the info. In this case I will play that type of files with MPV for seeking to avoid that problem.
