### ISSUE TITLE
Blacklisting Not Fully Functional

### ISSUE THREAD

**Issue by Voideka** [Nevcairiel/LAVFilters#170]
Blacklisting doesn't seem to work. Added an exe to all LAV blacklists, and it still crashes with LAV Filters 0.70.2. Game is 911 First Responders on Steam. It works when the filters are uninstalled. Win10.

**Comment by clsid2** [comment]
Blacklisting does not work when the splitter is set as preferred (read: forced) for a file extension. In that case DirectShow only tries using the preferred splitter, and doesn't fall back to trying others, so it is not something that can be fixed by LAV Filters.

Solution is to remove the Registry key that sets it as preferred.
HKEY_CLASSES_ROOT\Media Type\Extensions
HKEY_CLASSES_ROOT\Wow6432Node\Media Type\Extensions

I think that game uses .mpg videos? So removing that subkey should be enough (in addition to the blacklist).

**Comment by Nevcairiel** [comment]
clsid already explained the limitations of the blacklist system and DirectShow preferred filters. Can't really fix that.
