### ISSUE TITLE
Feature Request: Disable For Apps

### ISSUE THREAD

**Issue by LeeThompson** [Nevcairiel/LAVFilters#176]
I'd like a feature to be able to disable LAV Filters for specified applications. (i.e. whitelist)

Obviously the default behavior would be to disable whitelisting and just load for anything (as it presently does).

**Comment by Nevcairiel** [comment]
There is already a Blacklist feature to disable it for specified applications.

Create a DWORD key with the executable name in HKCU\Software\LAV\<filter>\Blacklist with any positive value (replace <filter> with Audio/Video/Splitter as appropriate)

Due to the nature DirectShow works,  Blacklisting of the Source Filter can be a bit tricky, because there can only be one source that handles a given file type, and if that one fails to open, it'll fail playback - easy solution is to not use the Source filter and rely on the splitter filter instead.

**Comment by LeeThompson** [comment]
Awesome, thanks!
