### ISSUE TITLE
about Splitter read data return S_False!

### ISSUE THREAD

**Issue by TopPlay** [Nevcairiel/LAVFilters#204]
lav Splitter use Custom source filter to read data,some time require length more than size -position;
so i return s_false; but graphibuilder receive EC_Complete message;
msdn:

Return code | Description
-- | --
S_FALSE | Retrieved fewer bytes than requested. (Probably the end of the file was reached.)
S_OK | Success.

**Comment by Nevcairiel** [comment]
If you return S_FALSE, then it'll consider the input stream to be at "End of File" and once all data is processed it'll send EC_COMPLETE. That seems to match the documentation just fine.

If you will have more data in the future, you should probably block and wait for that data, instead of returning S_FALSE.

**Comment by TopPlay** [comment]
My fault！I give wrong data!
_O_
