### ISSUE TITLE
Problem with the LAV Splitter Source

### ISSUE THREAD

**Issue by thompon** [Nevcairiel/LAVFilters#251]
Hello,
I have noticed a problem with the LAV Splitter Source filter.

When this filter is in a graph and receives data (UDP streaming for example), if there is no filter connected to its output for a short while (2 or 3 seconds), then once we connect the output, no video is displayed.

But if the output is connected quickly (less than 1 second) after the filter has started to receive UDP streaming, then the video is displayed normally.

It seems that the filter does not like to receive data for too long if there is nothing connected to its output.

If you could fix that, that would be wonderful. Thanks in advance.

**Comment by thompon** [comment]
any news about this issue?

**Comment by Nevcairiel** [comment]
LAV Splitter is primarily not designed as a streaming filter. These options are only offered because ffmpeg makes it easy to just expose them. All its internal dataflow is designed for file playback, and there are no plans to change that. It works well enough with simple streaming tasks, but UDP in particular is not "simple", as media data has to be buffered and gets lost easily when its not being "used".

Ultimately, why would you wait to connect? Seems like an easy fix on your side.

**Comment by thompon** [comment]
Thank you very much for your quick reply and for these details.

I need to wait to connect because I need the user to check if there is video only, audio only or both video and audio streams, before processing (and the user may change some parameters during this time interval).

I understand that this filter is mainly designed for files playback but actually it works very well with UDP and RTP so I was thinking that with a small change it would be able to work even if there is a delay between the detection of the input streams and the connection of the output.

Could it be a solution if I increased a lot the "Stream Analysis Duration" or the "Queue Settings" ?

By the way, the role of these parameters is not very clear for me. Is Stream Analysis Duration in milliseconds? How is it linked with the Queue Memory?

Thanks!

**Comment by Nevcairiel** [comment]
FFmpeg has an option to try to survive/recover from an overrun buffer, maybe you can try supplying that, and if it works I can look into making  LAV always set it.

Basically, you can add parameters in HTTP query syntax to the URL, like this:
udp://1.2.3.4?overrun_nonfatal=1

If you set this particular option (overrun_nonfatal), it'll keep overwriting its internal ring buffer. That may lead to a bit of corruption at the start of the stream, but should normalize and work.

**Comment by thompon** [comment]
Thank you a lot! I didn't know this option but it seems to be exactly what I was expecting. I am going to try it asap.

**Comment by mdcleaver** [comment]
This is a very strange issue and I think it must be affecting me. I have subtitling software on my PC and on my laptop. On the PC, video replay has stopped working and I get a black screen instead of the video. On the laptop it works fine. 
The difference is visible when I look at the filters on each, On the PC:
   Default DirectSound Device
   D:\Spot Videos\HEROES_TRAILER_EN_9_51.mp4 (source)
   LAV Video Decoder
   LAV Audio Decoder
   LAV Splitter Source (source)
   Video Renderer
The laptop works - and doesn't include the "LAV Splitter Source (source)".
How to disable it on the PC?
![image](https://user-images.githubusercontent.com/11269668/121667844-fc3c6680-caaa-11eb-8cff-139d93aa87ec.png)

**Comment by clsid2** [comment]
You are not streaming from the Internet. Your problem is a totally different one.

Your problem is caused by the video renderer. The application is using the system default "video renderer" filter, which is the ancient Video Mixer Renderer 7 filter. That one has compatibility issues on Windows 10 with NVIDIA drivers.

You can fix it by letting your application use a different video renderer. For example Video Mixer Renderer 9. If your application does not offer an option for this, then do this:
GraphStudioNext application > Menu > Graph > Insert Filter > Video Mixer Renderer 9 > Change merit > 0x00800002
