### ISSUE TITLE
MJPEG->NV12 or YV12 outputs in full-range colors (PC)

### ISSUE THREAD

**Issue by elwongest** [Nevcairiel/LAVFilters#266]
When decoding MJPEG to YV12, NV12, and possibly other YUV formats, the output is in full (PC) color range instead of TV color range. Rendering or re-encoding to H264 is not in accurate colors without post-processing the output of the LAV Video decoder.

There is an option for TV range when decoding in RGB, but no such option for YUV.

**Comment by Nevcairiel** [comment]
This is intended behavior. Output in the same colorspace as the file is decoded in will not touch the levels and always leave them untouched. The range option is only effective when a conversion to RGB is being performed, since the range is a simple factor in the formula.

LAV Video is not a processor, but a decoder. If you want to change the range for further processing, you'll need to do that seperately.

**Comment by elwongest** [comment]
Ok thanks for the quick response.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
