### ISSUE TITLE
LAV Splitter hanging

### ISSUE THREAD

**Issue by talbotmcinnis** [Nevcairiel/LAVFilters#301]
I am having an issue with LAV 0.74.1 on certain systems.  I have called graph->run(), and the graph reports it is running, but the graph is not progressing (no frames displayed, no more data being requested from the upstream filter, zero progress on the time remaining.  I have captured dump files of the filter in this stuck state, but its a 364 MB zip so I'm not sure where you would prefer it to be placed.  The most suspect part to me is a thread stuck on OutputPin.cpp:344.

This may be related to a fix I needed to add to my upstream source filter, which caught LAV splitter asking for data beyond the end of the end of the file.  The following code was required in that case to avoid a massive performance hit when switching to LAV:

`// LAV splitter was caught requesting bytes beyond the end of the file.
// If we find such a request, correct the request

if( GetDecryptedOut_BodyPosition() + dwBytesToRead > m_dwDecryptedBodySize )
{
	
dwBytesToRead = m_dwDecryptedBodySize - GetDecryptedOut_BodyPosition();
	Logger::Log(Logger::llDEBUG, TEXT("UID %u Invalid dwBytesToRead.  Resized to %u"), _dwUID, dwBytesToRead);
}`

**Comment by Nevcairiel** [comment]
If its stuck in OutputPin.cpp:344 then your downstream filters are not consuming any data, which is why the queues are full and that sleep condition is being triggered.

Regarding EOF reads, the API does not actually forbid calling it with any arbitrary position or size, and you are free to return a short read if the file is at EOF, or no read at all - as long as you return S_FALSE if you cannot return the full requested bytes, per the API definition.

Some othe readers for live sources will not properly report data in the Length call, so trying to read more is the only way to get all available data.
