### ISSUE TITLE
One step of installer says "Downloading"

### ISSUE THREAD

**Issue by wrzwicky** [Nevcairiel/LAVFilters#312]
When running the LAVfilters-installer, one step of the progress meter says "Downloading", which sounds very much like a virus or malware. There's no reason for the installer to download anything extra, I've already downloaded the installer.

If in fact the installer is not downloading anything, please change that word to be more accurate. If you are downloading something, PLEASE STOP and place those files into the installer, then change that word. Thank you!

**Comment by Nevcairiel** [comment]
The installer will download something when you enable the 3D MVC decoder, which is not enabled by default and also says "extra download" behind it. Since that component rarely, if ever, changes, it makes no sense to include it in an installer that changes much more frequently (and its also quite large)

So in short, It'll continue to perform the download if that option is enabled.
