### ISSUE TITLE
LAV Filter HEVC UHD 60fps issue

### ISSUE THREAD

**Issue by mchen30** [Nevcairiel/LAVFilters#340]
Intel graphics P630 (HD630 equivalent) + Nvidia M1200 cannot decode hevc uhd 50/60fps smoothly in MPC-BE. The decoder queue in MadVR is empty, so the problem is that the HEVC decoding is too slow. I'm using D3D11 copyback mode - the only one that supports using Intel iGPU to decode and Nvidia dGPU to render. HEVC UHD 30fps works perfectly fine. Is there an inherent memory bandwidth bottleneck, or is it a software optimization issue that might be fixed? I can't use Nvidia dGPU to decode HEVC UHD so I'm stuck with D3D11 copyback mode if I want to use MadVR. I'm pretty sure that Intel P630 can decode HEVC UHD at 100fps+. I'm using dual-channel DDR4 2400 memory. 

Thanks so much for any help.

**Comment by Nevcairiel** [comment]
Copy Back is inherently slow. There is no solution to that. Use a "Native" decoding mode for performance on a mobile device.

**Comment by mchen30** [comment]
Thanks for the info. But why is it slow? DDR4 bandwidth is much higher than 4k 10bit raw data stream. Is there any inherent reason (memcpy for Intel GPU, how the data pipeline is constructed) that would rule out any possibility of 60fps UHD copyback ever working? Maybe there's something about mobile device that makes it so?...

**Comment by Nevcairiel** [comment]
You can try DXVA2 Copy-Back, its usually faster then D3D11 Copy-Back, but its as optmized as it can be, really. You still end up copying the image at least twice, and the reason image downloads are slow is because thats not a typical use-case for video hardware. Images stored in video memory is usually not in the same format as it would be stored in system memory, so when you try to access it directly it needs to be transparently translated, which adds to the performance cost.

**Comment by mchen30** [comment]
> You can try DXVA2 Copy-Back, its usually faster then D3D11 Copy-Back, but its as optmized as it can be, really. You still end up copying the image at least twice, and the reason image downloads are slow is because thats not a typical use-case for video hardware. Images stored in video memory is usually not in the same format as it would be stored in system memory, so when you try to access it directly it needs to be transparently translated, which adds to the performance cost.

That's very interesting, thank you for the explanation. I can't use DXVA2 copy-back, for it only shows two duplicate entries of the Nvidia GPU (when dGPU is enabled in Nvidia tool). So I'm stuck with D3d11 if i want to use iGPU+dGPU at all for HEVC 4k (quicksync doesn't support hevc uhd).

Downloading twice doesn't seem that expensive. DDR4 2400 dual channel should have >200Gbps bandwidth, while, according to a "4K Data Rate Calculator", 4k50p is only 11Gbps. 

Intel Graphics "video memory" is also essentially system memory. Maybe something can be done to avoid unnecessary copying in the same hardware? I tried to look into the source code but to no one's surprise couldn't make sense of much low-level details let alone find anything relevant to my question. My hope is that there is some software optimization that can be done to make things work, but if we know for sure that the numbers don't work out for some deep reason, then I can drop this thought for good. It's just a shame that my system can't play 4k hevc 50/60fps when the iGPU can easily decode 100+fps.

**Comment by Nevcairiel** [comment]
That video memory uses the same physical memory really doesn't make a difference, since its virtually quite shut off and as mentioned above the layout of data in video memory is quite different to better match how a graphics chip works (usually organized in tiles). That is where the majority of the performance hit comes from.

On top of that, D3D11 Copy-Back is quite simply slower - oddly enough because D3D11 itself is more optimized. Due to that, it doesn't allow direct reading of a texture, to do that you need to copy the texture onto a special texture variant suited for reading, so in a D3D11 case you actually do 3 copies, iGPU -> iGPU -> System -> dGPU. DXVA2 Copy-Back does not require this, which allows it to be faster at times - but you can't access an "unconnected" GPU from DXVA2.

Either way, this has been optimized over several years already. Mobile hardware is just not suitable for such tasks. I would recommend to just play solely on the iGPU.

**Comment by mchen30** [comment]
Thanks so much again. I can imagine how the tiling would cause performance issues in copying as well as the texture memory problem. How is desktop different in this regard? Is it just because it's easier to upgrade the dGPU? As it is I'll take your advice and not use MadVR for the HEVC UHD 50/60fps materials.

**Comment by Nevcairiel** [comment]
A desktop with an iGPU would likely face similar problems, although you can force the iGPU to be active there so DXVA2 works with tricks.

Dealing with UHD 50/60 FPS content, doing any sort of copy of the data can easily cause a bottleneck on most systems.

**Comment by mchen30** [comment]
Thank you again for taking the time to explain this. I've been using the LAV filters for years and it's a great thing that they exist - I admire your expertise and dedication to this project, and I'm sure numerous others will continue to benefit from it.
