### ISSUE TITLE
Font issue when having ordered chapters/segment linking

### ISSUE THREAD

**Issue by eXmendiC** [Nevcairiel/LAVFilters#356]
See here: https://github.com/clsid2/mpc-hc/issues/549

**Comment by Nevcairiel** [comment]
Can't do anything without an example. As far as I can tell from the code, it should attempt to read attachments from all segments.

**Comment by eXmendiC** [comment]
Here is a sample file: https://github.com/mpv-player/mpv/issues/6503
mpv had the same issue, but fixed it. I can reconstruct the same issue here with that sample (using MPC-HC.1.9.6.x64).

**Comment by Nevcairiel** [comment]
I investigated this for a bit and found one bug that I fixed. LAV Splitter loads the font just fine, and it now also forwards style changes to the subtitle renderer at the appropriate time.

However, the subtitle renderer does not seem to handle style changes at packet boundaries properly and will always render with the last received style, which in this case is the one for the "end" segment, since it buffers events ahead quite a bit.

I don't think I can fix this on my end any further.
