### ISSUE TITLE
Audio drop outs when bitstreaming TrueHD 96kHz content on LAV Audio >0.73.1

### ISSUE THREAD

**Issue by JUGGStheOG** [Nevcairiel/LAVFilters#370]
I recently had to change AVRs as my Pioneer Elite SC-63 caught the dreaded "UE22" error. Replaced the SC-63 with the Denon AVR-X2600H.

When bitstreaming (HDMI) to the new AVR all tested 96kHz TrueHD content has consistent audio drop outs. Oddly no audio drop outs were produced with using the SC-63. No idea what that means.

Tested Content: (Untouched remuxes in MKV container)
Oblivion (2013) – BD contains a 5.1 16bit 96kHz TrueHD Isolated score track.
Dave Matthews and Tim Reynolds Live at Radio City (2007) – BD contains a 5.1 24bit 96kHz TrueHD track.

Also tested 96kHz DTSMA content from Léon: The Professional. This 96kHz content plays back without audio drop outs.

Tested LAV Audio versions 0.72.0, 0.73.1, 0.74.0, 0.74.1, and 0.74.1.64. All versions above 0.73.1 produce this audio drop out. Version 0.73.1 and below play the content without issue.

System:
Win10 Pro v.2004
GeForce GTX 650 Ti BOOST running driver version 456.71
HDMI to Denon AVR-X2600H
MPC-HC 1.9.7 and Kodi 17.6 (DSplayer edition) both exhibit the audio drop outs if running an affected version of LAV's audio filter.

Please let me know if you need any more information.

Thank you for your time and your wonderful product!

**Comment by aoaaron** [comment]
Just watched Star Wars and got some dropouts too. Annoying.

**Comment by JUGGStheOG** [comment]
> Just watched Star Wars and got some dropouts too. Annoying.

Do you happen to have any additional information? What was the audio format? What player and AVR?

Thanks!

**Comment by Nevcairiel** [comment]
When this happens it is likely that the remux into MKV is actually not flawless. TrueHD is special, it carries special continuity markers similar to timestamps, and if its remuxed from a Blu-ray, especially one with seamless branching, the muxing application might have to update those. Neglecting to do that can result in small glitches in bitstreaming.

Unfortunately once its remuxed, there is no reliable way to actually differentiate a wrong mux from an intentional gap.
