### ISSUE TITLE
AVC H.264 Level 6 Hardware Acceleration

### ISSUE THREAD

**Issue by 007licensed** [Nevcairiel/LAVFilters#374]
My AVC Codec Vids up to High@5.2 get proper Hardware Acceleration via DXVA2...
But High@6 and above = no  Hardware Acceleration
Any way to get  Hardware Acceleration working ???

https://ibb.co/9V0qNNt
https://ibb.co/WxSpjFJ

**Comment by clsid2** [comment]
The answer is NO. Profile 6 is not compatible with hardware decoding.

https://github.com/Nevcairiel/LAVFilters/issues/363

**Comment by 007licensed** [comment]
Ok, recent version has hw disabled...
So older version can handle profile@6 hw acceleration ?
So what version do support it?

**Comment by clsid2** [comment]
0.74.1 might work. But it was disabled for a reason: you are very likely to get decoding errors or artifacts!

**Comment by ValZapod** [comment]
> you are very likely to get decoding errors or artifacts

Then it is a bug in the driver.

**Comment by Nevcairiel** [comment]
> Then it is a bug in the driver. Just like there is (was) a bug in Nvidia driver to decode 5K hevc. It is normal, more or less. Sorry to disappoint.

Its not a bug in the driver if you try to send it a bitstream that it does not support. Its the softwares responsibility to check hardware support against the bitstream at hand, before trying to ask the hardware to decode it.

H.264 Level 6 exceeds the allowed DPB size of the hardware, and thus it cannot fully reference all reference frames, resulting in corrupted decoding. Therefor, a stream with that many reference frames should not be send to the hardware in the first place.

It might be possible to check number of reference frames independently of the level, so that level 6 can still be played back if it does not use a high number of reference frames.

**Comment by ValZapod** [comment]
Just FUI. A lot of ref frames are supported by cuda hwaccels (eleven here, profile 5 AVC) (previously nvdec) you just can get a warning, which is fixed by --threads 3

```
[h264 @ 00000215e6507580] decoder->cvdl->cuvidCreateDecoder(&decoder->decoder, params) failed -> CUDA_ERROR_INVALID_VALUE: invalid argument
[h264 @ 00000215e6507580] Using more than 32 (33) decode surfaces might cause nvdec to fail.
[h264 @ 00000215e6507580] Try lowering the amount of threads. Using 4 right now.
[h264 @ 00000215e6507580] Failed setup for format cuda: hwaccel initialisation returned error.
```

I suppose it is a bug, since every other thread just uses 1 decode surface after 3 that uses 32 out of 32. https://trac.ffmpeg.org/ticket/8948

But maybe it is what it is.
