### ISSUE TITLE
Don't load embedded font if it is already installed

### ISSUE THREAD

**Issue by clsid2** [Nevcairiel/LAVFilters#398]
Example where this caused a problem:
https://github.com/clsid2/mpc-hc/issues/958

Checking if a font is installed can be done via the Registry:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts

**Comment by Nevcairiel** [comment]
I have no information about the name of a font to reliably do such a check. Filenames are not guaranteed to have any particular meaning, and the font name itself is not information I have access to.

**Comment by ale5000-git** [comment]
@clsid2: I think there should be a protection about the font used in the interface hardcoded in the player itself.
A malicious directshow filter could potentially load a specially crafted font with inverted letters and so change menu text of MPC-HC.
I'm not sure about other security implications but I think it should be avoided at player level since LAVFilters isn't the only filter used.

**Comment by ValZapod** [comment]
Wow, you cannot be serious. The player must use the embedded font. Always. Wow. While mpv is working on fixing their issues with embedded fonts, you are doing the opposite...
