### ISSUE TITLE
libbluray update

### ISSUE THREAD

**Issue by ale5000-git** [Nevcairiel/LAVFilters#407]
Hi,
could you please update libbluray to version 1.2.1?

This is just a reminder :)

PS: There will be menu support in the future? (libbluray already support them if I'm not wrong)

**Comment by Nevcairiel** [comment]
Menus are not planned.

And nothing in LAV really benefits from any recent changes in libbluray, since thats like 100% menu work. I'll probably update it at some point when I do scheduled re-working on the Blu-ray demuxer.

If there is a particular bug I have missed, please report those instead of asking for blanket library upgrades with no explanation.

**Comment by ale5000-git** [comment]
I'm not sure what parts of libbluray are used but these seems useful (from 1.2.1 changes):
[Always inform application about current streams when playlist is started](https://code.videolan.org/videolan/libbluray/-/commit/a284de9b6961c52f51138279bad28b7af9b6344a)
[bdnav: regonize fmts files](https://code.videolan.org/videolan/libbluray/-/commit/2dfe914fb53e9d689264a4fc48bb747941255c4d)
