### ISSUE TITLE
DASH Manifest stream selection

### ISSUE THREAD

**Issue by clsid2** [Nevcairiel/LAVFilters#416]
There are some issues with playback of DASH Manifests from YouTube. URL extracted with youtube-dl.

First issue is that there are multiple video streams that are flagged as default. LAV selects the first one. Preferably it should pick the one with best quality.
![dash_example](https://user-images.githubusercontent.com/4704996/117490329-ecdb7200-af6e-11eb-9438-9ee57d2c9101.png)

Another issue is that sound goes mute after a few seconds. It comes back after a seek.

Finally, it can contain both H264 and VP9 streams. Switching format does not work well.

**Comment by clsid2** [comment]
There are some YT videos (non-live) where only a few "normal" streams are available and only in low quality. The 720p and above were only available as DASH. So it some (rare) cases there isn't a better alternative. Seeking did work however.

MPC-HC currently completely ignores DASH streams.

**Comment by kasper93** [comment]
Do you have good sample link? I have my few lines script to extract audio and video link and run player. And for years didn't find a video where good quality was available only in segmented video in dash manifest (well I don't watch that much YT). I was looking now and found indeed one with segmented variant, but normal (separated, but in whole chunk) one was also available with good quality.

Anyhow stream selection can be improved indeed as currently first default stream will be selected always, little adjustment to compare default ones between each other instead of break on first here https://github.com/Nevcairiel/LAVFilters/blob/ddef56ae155d436f4301346408f4fdba755197d6/demuxer/Demuxers/LAVFDemuxer.cpp#L2734-L2738

Also from quick test this change https://github.com/Nevcairiel/LAVFilters/commit/cc5d58fd87ce52f5cfce81249f2506c096641a8f prevents from selecting higher bit-rate one, but well question is whether it should be re-enabled.

I tested with this with this local changes
``` diff
diff --git a/demuxer/Demuxers/LAVFDemuxer.cpp b/demuxer/Demuxers/LAVFDemuxer.cpp
index 6e5004d1..ac1cc129 100644
--- a/demuxer/Demuxers/LAVFDemuxer.cpp
+++ b/demuxer/Demuxers/LAVFDemuxer.cpp
@@ -2731,17 +2731,22 @@ const CBaseDemuxer::stream *CLAVFDemuxer::SelectVideoStream()
     {
         stream *check = &*it;
 
-        if (m_avFormat->streams[check->pid]->disposition & AV_DISPOSITION_DEFAULT)
+        if (!best)
         {
             best = check;
-            break;
+            continue;
         }
 
-        if (!best)
+        bool checkDefault = m_avFormat->streams[check->pid]->disposition & AV_DISPOSITION_DEFAULT;
+        bool bestDefault = m_avFormat->streams[best->pid]->disposition & AV_DISPOSITION_DEFAULT;
+
+        if (checkDefault ^ bestDefault)
         {
-            best = check;
+            if (checkDefault)
+                best = check;
             continue;
         }
+
         uint64_t bestPixels = (uint64_t)m_avFormat->streams[best->pid]->codecpar->width *
                               m_avFormat->streams[best->pid]->codecpar->height;
         uint64_t checkPixels = (uint64_t)m_avFormat->streams[check->pid]->codecpar->width *
@@ -2775,7 +2780,7 @@ const CBaseDemuxer::stream *CLAVFDemuxer::SelectVideoStream()
             {
                 best = check;
             }
-            else if (m_bRM && checkPixels == bestPixels)
+            else if (checkPixels == bestPixels)
             {
                 int64_t best_rate = m_avFormat->streams[best->pid]->codecpar->bit_rate;
                 int64_t check_rate = m_avFormat->streams[check->pid]->codecpar->bit_rate;

```

**Comment by clsid2** [comment]
I was given this example:
https://www.youtube.com/watch?v=QNLvm-oCz_Q

**Comment by Nevcairiel** [comment]
LAV should now favor the highest resolution stream if multiple video streams are marked as default

**Comment by ale5000-git** [comment]
@Nevcairiel
When there are 2 streams with the same format and resolution (but different bitrate) it choose the first not the one with best quality.

Sample: https://www.wittytv.it/uomini-e-donne/lunedi-30-novembre/
