### ISSUE TITLE
Questions about the interlace flags

### ISSUE THREAD

**Issue by CrendKing** [Nevcairiel/LAVFilters#433]
Hi. I'm the author of [AVSF](https://github.com/CrendKing/avisynth_filter/), a downstream filter of LAV Video Decoder. I'm trying to understand the output of the two interlace flags that LVD generates.

First is the [`VIDEOINFOHEADER2::dwInterlaceFlags`](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/api/dvdmedia/ns-dvdmedia-videoinfoheader2). The `AMINTERLACE_Field1First` bit says if set it's the field 1 first, where "The top field in PAL is field 1, and the top field in NTSC is field 2" (I don't know how to tell the video being PAL or NTSC deterministically). However, in [CLAVVideo::ReconnectOutput()](https://github.com/Nevcairiel/LAVFilters/blob/master/decoder/LAVVideo/LAVVideo.cpp#L1293), that bit is never set. So as a downstream, should I completely ignore the field order in the media type level?

Second is [AM_SAMPLE2_PROPERTIES::dwTypeSpecificFlags](https://docs.microsoft.com/en-us/windows/win32/api/strmif/ns-strmif-am_sample2_properties). [CDecAvcodec::DecodePacket()](https://github.com/Nevcairiel/LAVFilters/blob/master/decoder/LAVVideo/decoders/avcodec.cpp#L1306) sets the relevant info here into LAVFrame. Then in [CLAVVideo::SetFrameFlags()](https://github.com/Nevcairiel/LAVFilters/blob/master/decoder/LAVVideo/LAVVideo.cpp#L2460) uses the info to produce `dwTypeSpecificFlags`. It does sets `AM_VIDEO_FLAG_FIELD1FIRST`, however, how do I know field 1 is top field or bottom field? Why do you only set the field order per frame but not in media type? Could field order change across frames without changing media type?

Also, I don't understand
```
if (!pFrame->interlaced)
    props.dwTypeSpecificFlags |= AM_VIDEO_FLAG_WEAVE;
```
According to the AM_SAMPLE2_PROPERTIES doc, if frame is not interlaced, shouldn't the first two bits (applying `AM_VIDEO_FLAG_FIELD_MASK` mask) be 0 (which is the default)? And if it is interlaced, the two bits should be either value 1 (field 1) or value 2 (field 2), right? But I never see these values set in LAVVideo.cpp. And shouldn't the deinterlacing mode being weave or bob mode comes from a separate information (like what `dwInterlaceFlags` has)? How does downstream know if the current sample is field 1 or 2?

Or maybe I'm misunderstanding something, like all samples after LVD are already deinterlaced and those flags are only relevant in the raw video data?

**Comment by Nevcairiel** [comment]
The media type does not convey the field order because its not reliably known at media type creation, and/or can vary. Deinterlace flags will typically either be 0 for 100% progressive, or AMINTERLACE_IsInterlaced | AMINTERLACE_DisplayModeBobOrWeave for mixed or interlaced content. These flags instruct any downstream filter to check the media sample flags, instead of having a global flag for every sample.

Samples always contain both fields weaved together, hence AM_VIDEO_FLAG_FIELD_MASK is 0 (= AM_VIDEO_FLAG_INTERLEAVED_FRAME), and the field1/2 bits are never set. Furthermore, AM_VIDEO_FLAG_FIELD1FIRST is set if the top field should be displayed first (the interleaved field starting with the first line), or if its not set, the bottom field should be displayed first (the interleaved field starting with the second line). Or when AM_VIDEO_FLAG_WEAVE is set, no deinterlacing is required, eg. its progressive.

Which field is top or bottom is not a question here, as the interleaving has already clarified that, only the display order is now relevant.

I just re-checked Microsofts documentation on VIDEOINFOHEADER2 as well as AM_SAMPLE2_PROPERTIES, and I'm confident that this behavior and flagging is fully conformant. Of course this also work with Microsofts Enhanced Video Renderer to properly invoke deinterlacing only when required.

**Comment by CrendKing** [comment]
So if AMINTERLACE_IsInterlaced in media type is not set, I can determine the frames are progressive. Otherwise it's interlaced and I should check the sample flags for details?

So for all frames downstream receives, field order doesn't matter and only display order matters? Gotcha. Basically combining AM_VIDEO_FLAG_FIELD1FIRST and AM_VIDEO_FLAG_WEAVE to know which one of the three orders should be used:

* 1, 3, 5, 7, 2, 4, 6, 8
* 2, 4, 6, 8, 1, 3, 5, 7
* 1, 2, 3, 4, 5, 6, 7, 8

Right?

So are those field order flags designed for different kind of filters, like those handling signals from VHS, VCD devices?

**Comment by Nevcairiel** [comment]
The odd lines always create one field, and the even lines always create one field. Which one is first in "display order" is controlled by the flag (either top first = tff, or bottom first = bff). Not sure how you treat fields, but interleaved fields inside a single frame is rather common in any video APIs I have touched, be it from ffmpeg or any hardware APIs.

I suppose theoretically any kind of content could be decoded into distinct fields, and DirectShow would allow you to send it along like that, but I have never seen any software do that.

**Comment by CrendKing** [comment]
Thanks. Everything works.

**Comment by ValZapod** [comment]
> have never seen any software do that

It is literally a bug now for interlaced hevc in ffmpeg. Also PAFF is still WIP in x264.
