### ISSUE TITLE
Video is small when using LAV Splitter Source in Potplayer

### ISSUE THREAD

**Issue by fmnijk** [Nevcairiel/LAVFilters#532]
Note that the video is NSFW. I cannot find a SFW example, sorry.

I download the video here:
https://www.hotpowers.jp/ec/upload/save_image/video/hop57-cut.mp4

As you can see, when I use LAV Splitter Source in Potplayer, it is really small.
When I turn off LAV Splitter Source only, turn on LAV Video Decoder and LAV Audio Decoder. It works fine.
![](https://user-images.githubusercontent.com/52465927/216627042-9076470b-6ebe-4dae-b4d3-64c3556e1f1c.png)

It seems like the video itself has some problem because the thumbnail in Windows 10 is also small. Even when it is set to large.

**Comment by Nevcairiel** [comment]
There is nothing special going on with that video in LAV. It has a rather bizarre aspect ratio, but thats coming from the container and just being passed through by LAV - and its perfectly valid to have weird numbers there.

I did some cleanup of the aspect ratio values, if that is in fact the cause, but otherwise there is nothing wrong here.
