### ISSUE TITLE
Freezes the Player after using LAV Filter for some time 

### ISSUE THREAD

**Issue by Gajanana** [Nevcairiel/LAVFilters#95]
I have 2 media engines to decode two  video files seperately and content is changed and Directshow graph is destroyed and rebuilt(This is the feature) .After using LAV filter as a splitter in my application for 2-3 hours Application freezes(for mp4/mov). This issue is not observed with any other filter like InfoValue,Elecard ,Medialooks Qt source, Directshow filters which comes with windows etc .

**Comment by Nevcairiel** [comment]
Many other players constantly create and destroy DirectShow graphs and play videos over several hours, and have no such troubles. Since this is showing up with your application, you would need to provide more information, otherwise there isn't anything I could even start with to look into any potential problems.

Unfortunately a report "it freezes with my application" doesn't really help me to even guess what might be the issue.

**Comment by Nevcairiel** [comment]
Closed due to lack of feedback, please re-open if you can provide any conclusive information or reproducible test-cases.
